### PR TITLE
9.2.2 fix

### PR DESCRIPTION
**Pull request by NerdyParker**

### CODE REVIEW

**Comment by NerdyParker** [comment]
Sorry - please ignore.

**Comment by RichardHowells** [comment]
Hi @NerdyParker,

I'm puzzled - or more likely don't know enough about GitHub.  It looks to me like you made a *lot* of valuable changes in your 9.2.2.-fix branch, that have not made it back to the Ventrian:master branch.

I'm interested in contributing to maintaining this module, and it's not clear to me where best to start.  Your fork or the original?

The original won't build because it's missing stuff that ImageHandler.ashx requires. :-(

It looks to me like there are some other efforts but they are fragmented.

I see @jaxuk looks to be working in it; @sjmcculloch mentioned he was doing a patch; @cklenk was asking about libraries so I guess is interested too.

Who wants to join a team, so we can make a plan, and do something really useful together?

**Comment by nvisionative** [comment]
@RichardHowells you bring up some GREAT points.  Perhaps @sjmcculloch would be interested in migrating this project to the DNN Community org on GitHub for greater visibility and ongoing contributions.  There is a huge effort going on right now to rally the DNN Community to work on these old "core" modules and some newer ones.

**Comment by RichardHowells** [comment]
We clearly have most of the source.  It looks like there are some who have found workarounds to the "won't build" issue - or maybe just are not building the whole thing.

The biggest gift that Scot (@sjmcculloch) could give us is the instructions for creating an install package.  From a glance it's clearly more complex than the average module.  Scott clearly worked out a recipe.  It would be a shame if that knowledge was lost and had to be painfully reverse engineered (AKA trial and error guesswork).

**Comment by NerdyParker** [comment]
@RichardHowells @nvisionative - My source is [here](https://github.com/NerdyParker/News-Articles) but I wasn't able to correctly package it because I don't have the correct build script. I was able to get it working by installing the current Ventrian News Articles module, and then overwriting the Ventrian.NewsArticles.dll with the compiled version of my repository.

**Comment by nvisionative** [comment]
Ah okay.  Hopefully @sjmcculloch will have time to chime in soon and bring some clarity.  I know quite a few that would love to see this project thrive.  With all the great activity going on in the [DNN Community GitHub org](https://github.com/DNNCommunity), I can't help but to think there could be some great synergy to help this repo.  NA has been a trusted solution for so long and now people are having to rely on other commercial modules to accomplish some of the same things this solution provides.  @sjmcculloch just let us know if we can help in any way - hope you are doing well!

**Pull request closed without merging**
